#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-tinycss2
Version  : 1.1.1
Release  : 9
URL      : https://files.pythonhosted.org/packages/1e/5a/576828164b5486f319c4323915b915a8af3fa4a654bbb6f8fc8e87b5cb17/tinycss2-1.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/1e/5a/576828164b5486f319c4323915b915a8af3fa4a654bbb6f8fc8e87b5cb17/tinycss2-1.1.1.tar.gz
Summary  : A tiny CSS parser
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-tinycss2-license = %{version}-%{release}
Requires: pypi-tinycss2-python = %{version}-%{release}
Requires: pypi-tinycss2-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)
BuildRequires : pypi(webencodings)

%description
tinycss2 is a low-level CSS parser and generator written in Python: it can
parse strings, return objects representing tokens and blocks, and generate CSS
strings corresponding to these objects.

%package license
Summary: license components for the pypi-tinycss2 package.
Group: Default

%description license
license components for the pypi-tinycss2 package.


%package python
Summary: python components for the pypi-tinycss2 package.
Group: Default
Requires: pypi-tinycss2-python3 = %{version}-%{release}

%description python
python components for the pypi-tinycss2 package.


%package python3
Summary: python3 components for the pypi-tinycss2 package.
Group: Default
Requires: python3-core
Provides: pypi(tinycss2)
Requires: pypi(webencodings)

%description python3
python3 components for the pypi-tinycss2 package.


%prep
%setup -q -n tinycss2-1.1.1
cd %{_builddir}/tinycss2-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641943148
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-tinycss2
cp %{_builddir}/tinycss2-1.1.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tinycss2/26c7c8914cec0f36ce51a3d106cb8b51cdbb5fac
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-tinycss2/26c7c8914cec0f36ce51a3d106cb8b51cdbb5fac

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
